services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  frances-api:
    image: damonyudocker/frances-api:v2.2.0
    ports:
      - "5000:5000"
    volumes:
      - /home/damonyu/.config/gcloud/application_default_credentials.json:/gcp/creds.json
      - /home/damonyu/ca/elastic_ca.crt:/web_app/query_app/certs/elastic_ca.crt
    environment:
      - FRANCES_FRONT_DOMAIN=www.frances-ai.com
      - FRANCES_FRONT_PORT=80
      - KG_BASE_URL=http://query.frances-ai.com/
      - PROJECT_ID=frances-365422
      - CLUSTER_NAME=cluster-8753
      - CLUSTER_REGION=us-central1
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp/creds.json
      - ELASTICSEARCH_API_KEY=${ELASTICSEARCH_API_KEY}
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
    depends_on:
      database:
        condition: service_started
  frances-front:
    image: damonyudocker/frances-front:v2.2.0
    ports:
      - "80:80"
    environment:
    - REACT_APP_FRANCES_API_ADDRESS=http://www.frances-ai.com:5000/api/v1
    depends_on:
      frances-api:
        condition: service_started
