services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=frances
      - POSTGRES_PASSWORD=frances
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  frances-api:
    image: damonyudocker/frances-api:v2
    ports:
      - "5000:5000"
    volumes:
      - /home/damonyu/.config/gcloud/application_default_credentials.json:/gcp/creds.json
    environment:
      - FRANCES_FRONT_DOMAIN=www.frances-ai.com
      - FRANCES_FRONT_PORT=80
      - KG_BASE_URL=http://34.70.98.82:80/
      - PROJECT_ID=frances-365422
      - CLUSTER_NAME=cluster-8753
      - CLUSTER_REGION=us-central1
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp/creds.json
    depends_on:
      database:
        condition: service_started
  frances-front:
    image: damonyudocker/frances-front:v2
    ports:
      - "80:80"
    environment:
    - REACT_APP_FRANCES_API_ADDRESS=http://www.frances-ai.com:5000/api/v1
    depends_on:
      frances-api:
        condition: service_started
