# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: defoe.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x64\x65\x66oe.proto\x12\x05\x64\x65\x66oe\"\xea\x01\n\x10JobSubmitRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x12\n\nquery_name\x18\x03 \x01(\t\x12\x10\n\x08\x65ndpoint\x18\x04 \x01(\t\x12>\n\x0cquery_config\x18\x05 \x03(\x0b\x32(.defoe.JobSubmitRequest.QueryConfigEntry\x12\x18\n\x10result_file_path\x18\x06 \x01(\t\x1a\x32\n\x10QueryConfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"#\n\x11JobSubmitResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"\x1c\n\nJobRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"U\n\x0bJobResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t\x12\x18\n\x10result_file_path\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t2~\n\x05\x44\x65\x66oe\x12\x41\n\nsubmit_job\x12\x17.defoe.JobSubmitRequest\x1a\x18.defoe.JobSubmitResponse\"\x00\x12\x32\n\x07get_job\x12\x11.defoe.JobRequest\x1a\x12.defoe.JobResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'defoe_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _JOBSUBMITREQUEST_QUERYCONFIGENTRY._options = None
  _JOBSUBMITREQUEST_QUERYCONFIGENTRY._serialized_options = b'8\001'
  _JOBSUBMITREQUEST._serialized_start=23
  _JOBSUBMITREQUEST._serialized_end=257
  _JOBSUBMITREQUEST_QUERYCONFIGENTRY._serialized_start=207
  _JOBSUBMITREQUEST_QUERYCONFIGENTRY._serialized_end=257
  _JOBSUBMITRESPONSE._serialized_start=259
  _JOBSUBMITRESPONSE._serialized_end=294
  _JOBREQUEST._serialized_start=296
  _JOBREQUEST._serialized_end=324
  _JOBRESPONSE._serialized_start=326
  _JOBRESPONSE._serialized_end=411
  _DEFOE._serialized_start=413
  _DEFOE._serialized_end=539
# @@protoc_insertion_point(module_scope)
